### ISSUE TITLE
Add function to list registered players

### ISSUE THREAD

**Issue by margrietpalm** [daanveraart/dolfje#27]
Finding out who signed up to play is a hassle. It would be great to have a function like `/wwingeschreven`.

Expected results:
- `/wwingeschreven` when a game is active: list of players
- `/wwingeschreven` when no game is active: nothing or some kind of warning

**Comment by daanveraart** [comment]
you can use wwlijst for this, we have functionality that requires player interaction for a reason, we don't want to dilute this by adding functionally that undermines this

**Comment by margrietpalm** [comment]
Thanks, but as I understand it, this only works when the game is running because beforehand the players are not in any game channel. I think I didn't phrase my request right; as a verteller I would like to know who is registered to play before the game starts.
